const fs = require('fs');
const path = require('path');

const extractEntities = (dir, entities = new Set()) => {
    const files = fs.readdirSync(dir);
    for (const file of files) {
        const fullPath = path.join(dir, file);
        if (fs.statSync(fullPath).isDirectory()) {
            extractEntities(fullPath, entities);
        } else if (file.endsWith('.js') || file.endsWith('.jsx') || file.endsWith('.ts') || file.endsWith('.tsx')) {
            const content = fs.readFileSync(fullPath, 'utf8');
            const matches = content.matchAll(/rdsn\.(asServiceRole\.)?entities\.([A-Za-z0-9_]+)\./g);
            for (const match of matches) {
                entities.add(match[2]);
            }
        }
    }
    return entities;
};

const entities = extractEntities(path.join(__dirname, 'src'));
extractEntities(path.join(__dirname, 'functions'), entities);

let sql = `-- Supabase Automated Migration generated by Antigravity\n\n`;

for (const entity of entities) {
    sql += `CREATE TABLE IF NOT EXISTS public."${entity}" (\n`;
    sql += `  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),\n`;
    sql += `  created_at TIMESTAMPTZ DEFAULT now(),\n`;
    sql += `  j_data JSONB DEFAULT '{}'::jsonb -- Stores dynamic columns until strongly typed\n`;
    sql += `);\n\n`;

    // Enable RLS but allow everything for now since it's an internal admin tool
    sql += `ALTER TABLE public."${entity}" ENABLE ROW LEVEL SECURITY;\n`;
    sql += `DROP POLICY IF EXISTS "Allow All" ON public."${entity}";\n`;
    sql += `CREATE POLICY "Allow All" ON public."${entity}" FOR ALL USING (true) WITH CHECK (true);\n\n`;
}

fs.writeFileSync(path.join(__dirname, 'supabase_migration.sql'), sql);
console.log('Migration generated at supabase_migration.sql');
