-- Supabase Automated Migration generated by Antigravity

CREATE TABLE IF NOT EXISTS public."Alerta" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ DEFAULT now(),
  j_data JSONB DEFAULT '{}'::jsonb -- Stores dynamic columns until strongly typed
);

ALTER TABLE public."Alerta" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow All" ON public."Alerta";
CREATE POLICY "Allow All" ON public."Alerta" FOR ALL USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public."PermissaoRole" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ DEFAULT now(),
  j_data JSONB DEFAULT '{}'::jsonb -- Stores dynamic columns until strongly typed
);

ALTER TABLE public."PermissaoRole" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow All" ON public."PermissaoRole";
CREATE POLICY "Allow All" ON public."PermissaoRole" FOR ALL USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public."ConfiguracaoGeral" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ DEFAULT now(),
  j_data JSONB DEFAULT '{}'::jsonb -- Stores dynamic columns until strongly typed
);

ALTER TABLE public."ConfiguracaoGeral" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow All" ON public."ConfiguracaoGeral";
CREATE POLICY "Allow All" ON public."ConfiguracaoGeral" FOR ALL USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public."BackupHistorico" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ DEFAULT now(),
  j_data JSONB DEFAULT '{}'::jsonb -- Stores dynamic columns until strongly typed
);

ALTER TABLE public."BackupHistorico" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow All" ON public."BackupHistorico";
CREATE POLICY "Allow All" ON public."BackupHistorico" FOR ALL USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public."ReservaLote" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ DEFAULT now(),
  j_data JSONB DEFAULT '{}'::jsonb -- Stores dynamic columns until strongly typed
);

ALTER TABLE public."ReservaLote" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow All" ON public."ReservaLote";
CREATE POLICY "Allow All" ON public."ReservaLote" FOR ALL USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public."Cliente" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ DEFAULT now(),
  j_data JSONB DEFAULT '{}'::jsonb -- Stores dynamic columns until strongly typed
);

ALTER TABLE public."Cliente" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow All" ON public."Cliente";
CREATE POLICY "Allow All" ON public."Cliente" FOR ALL USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public."PCPOrdemProducao" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ DEFAULT now(),
  j_data JSONB DEFAULT '{}'::jsonb -- Stores dynamic columns until strongly typed
);

ALTER TABLE public."PCPOrdemProducao" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow All" ON public."PCPOrdemProducao";
CREATE POLICY "Allow All" ON public."PCPOrdemProducao" FOR ALL USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public."PCPProducaoDiaria" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ DEFAULT now(),
  j_data JSONB DEFAULT '{}'::jsonb -- Stores dynamic columns until strongly typed
);

ALTER TABLE public."PCPProducaoDiaria" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow All" ON public."PCPProducaoDiaria";
CREATE POLICY "Allow All" ON public."PCPProducaoDiaria" FOR ALL USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public."PCPCliente" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ DEFAULT now(),
  j_data JSONB DEFAULT '{}'::jsonb -- Stores dynamic columns until strongly typed
);

ALTER TABLE public."PCPCliente" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow All" ON public."PCPCliente";
CREATE POLICY "Allow All" ON public."PCPCliente" FOR ALL USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public."BaixaLote" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ DEFAULT now(),
  j_data JSONB DEFAULT '{}'::jsonb -- Stores dynamic columns until strongly typed
);

ALTER TABLE public."BaixaLote" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow All" ON public."BaixaLote";
CREATE POLICY "Allow All" ON public."BaixaLote" FOR ALL USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public."Setor" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ DEFAULT now(),
  j_data JSONB DEFAULT '{}'::jsonb -- Stores dynamic columns until strongly typed
);

ALTER TABLE public."Setor" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow All" ON public."Setor";
CREATE POLICY "Allow All" ON public."Setor" FOR ALL USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public."Produto" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ DEFAULT now(),
  j_data JSONB DEFAULT '{}'::jsonb -- Stores dynamic columns until strongly typed
);

ALTER TABLE public."Produto" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow All" ON public."Produto";
CREATE POLICY "Allow All" ON public."Produto" FOR ALL USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public."ConfiguracaoKPI" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ DEFAULT now(),
  j_data JSONB DEFAULT '{}'::jsonb -- Stores dynamic columns until strongly typed
);

ALTER TABLE public."ConfiguracaoKPI" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow All" ON public."ConfiguracaoKPI";
CREATE POLICY "Allow All" ON public."ConfiguracaoKPI" FOR ALL USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public."ConfiguracaoAlerta" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ DEFAULT now(),
  j_data JSONB DEFAULT '{}'::jsonb -- Stores dynamic columns until strongly typed
);

ALTER TABLE public."ConfiguracaoAlerta" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow All" ON public."ConfiguracaoAlerta";
CREATE POLICY "Allow All" ON public."ConfiguracaoAlerta" FOR ALL USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public."MovimentacaoEstoque" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ DEFAULT now(),
  j_data JSONB DEFAULT '{}'::jsonb -- Stores dynamic columns until strongly typed
);

ALTER TABLE public."MovimentacaoEstoque" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow All" ON public."MovimentacaoEstoque";
CREATE POLICY "Allow All" ON public."MovimentacaoEstoque" FOR ALL USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public."Notificacao" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ DEFAULT now(),
  j_data JSONB DEFAULT '{}'::jsonb -- Stores dynamic columns until strongly typed
);

ALTER TABLE public."Notificacao" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow All" ON public."Notificacao";
CREATE POLICY "Allow All" ON public."Notificacao" FOR ALL USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public."ProducaoDia" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ DEFAULT now(),
  j_data JSONB DEFAULT '{}'::jsonb -- Stores dynamic columns until strongly typed
);

ALTER TABLE public."ProducaoDia" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow All" ON public."ProducaoDia";
CREATE POLICY "Allow All" ON public."ProducaoDia" FOR ALL USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public."ProducaoDiaLote" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ DEFAULT now(),
  j_data JSONB DEFAULT '{}'::jsonb -- Stores dynamic columns until strongly typed
);

ALTER TABLE public."ProducaoDiaLote" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow All" ON public."ProducaoDiaLote";
CREATE POLICY "Allow All" ON public."ProducaoDiaLote" FOR ALL USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public."Auditoria" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ DEFAULT now(),
  j_data JSONB DEFAULT '{}'::jsonb -- Stores dynamic columns until strongly typed
);

ALTER TABLE public."Auditoria" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow All" ON public."Auditoria";
CREATE POLICY "Allow All" ON public."Auditoria" FOR ALL USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public."TemplatePDF" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ DEFAULT now(),
  j_data JSONB DEFAULT '{}'::jsonb -- Stores dynamic columns until strongly typed
);

ALTER TABLE public."TemplatePDF" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow All" ON public."TemplatePDF";
CREATE POLICY "Allow All" ON public."TemplatePDF" FOR ALL USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public."SequenciaAnual" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ DEFAULT now(),
  j_data JSONB DEFAULT '{}'::jsonb -- Stores dynamic columns until strongly typed
);

ALTER TABLE public."SequenciaAnual" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow All" ON public."SequenciaAnual";
CREATE POLICY "Allow All" ON public."SequenciaAnual" FOR ALL USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public."NumeracaoLivre" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ DEFAULT now(),
  j_data JSONB DEFAULT '{}'::jsonb -- Stores dynamic columns until strongly typed
);

ALTER TABLE public."NumeracaoLivre" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow All" ON public."NumeracaoLivre";
CREATE POLICY "Allow All" ON public."NumeracaoLivre" FOR ALL USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public."AuditoriaUsuarios" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ DEFAULT now(),
  j_data JSONB DEFAULT '{}'::jsonb -- Stores dynamic columns until strongly typed
);

ALTER TABLE public."AuditoriaUsuarios" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow All" ON public."AuditoriaUsuarios";
CREATE POLICY "Allow All" ON public."AuditoriaUsuarios" FOR ALL USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public."RegraAuditoria" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ DEFAULT now(),
  j_data JSONB DEFAULT '{}'::jsonb -- Stores dynamic columns until strongly typed
);

ALTER TABLE public."RegraAuditoria" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow All" ON public."RegraAuditoria";
CREATE POLICY "Allow All" ON public."RegraAuditoria" FOR ALL USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public."HistoricoAuditoria" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ DEFAULT now(),
  j_data JSONB DEFAULT '{}'::jsonb -- Stores dynamic columns until strongly typed
);

ALTER TABLE public."HistoricoAuditoria" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow All" ON public."HistoricoAuditoria";
CREATE POLICY "Allow All" ON public."HistoricoAuditoria" FOR ALL USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public."Etiqueta" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ DEFAULT now(),
  j_data JSONB DEFAULT '{}'::jsonb -- Stores dynamic columns until strongly typed
);

ALTER TABLE public."Etiqueta" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow All" ON public."Etiqueta";
CREATE POLICY "Allow All" ON public."Etiqueta" FOR ALL USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public."IntegracaoExterna" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ DEFAULT now(),
  j_data JSONB DEFAULT '{}'::jsonb -- Stores dynamic columns until strongly typed
);

ALTER TABLE public."IntegracaoExterna" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow All" ON public."IntegracaoExterna";
CREATE POLICY "Allow All" ON public."IntegracaoExterna" FOR ALL USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public."LogIntegracao" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ DEFAULT now(),
  j_data JSONB DEFAULT '{}'::jsonb -- Stores dynamic columns until strongly typed
);

ALTER TABLE public."LogIntegracao" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow All" ON public."LogIntegracao";
CREATE POLICY "Allow All" ON public."LogIntegracao" FOR ALL USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public."TarefaAgendada" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ DEFAULT now(),
  j_data JSONB DEFAULT '{}'::jsonb -- Stores dynamic columns until strongly typed
);

ALTER TABLE public."TarefaAgendada" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow All" ON public."TarefaAgendada";
CREATE POLICY "Allow All" ON public."TarefaAgendada" FOR ALL USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public."UsuarioInterno" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ DEFAULT now(),
  j_data JSONB DEFAULT '{}'::jsonb -- Stores dynamic columns until strongly typed
);

ALTER TABLE public."UsuarioInterno" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow All" ON public."UsuarioInterno";
CREATE POLICY "Allow All" ON public."UsuarioInterno" FOR ALL USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public."BloqueioIntervalo" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ DEFAULT now(),
  j_data JSONB DEFAULT '{}'::jsonb -- Stores dynamic columns until strongly typed
);

ALTER TABLE public."BloqueioIntervalo" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow All" ON public."BloqueioIntervalo";
CREATE POLICY "Allow All" ON public."BloqueioIntervalo" FOR ALL USING (true) WITH CHECK (true);

CREATE TABLE IF NOT EXISTS public."User" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ DEFAULT now(),
  j_data JSONB DEFAULT '{}'::jsonb -- Stores dynamic columns until strongly typed
);

ALTER TABLE public."User" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow All" ON public."User";
CREATE POLICY "Allow All" ON public."User" FOR ALL USING (true) WITH CHECK (true);

